apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: prometheus-crds
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: monitoring
    server: https://kubernetes.default.svc
  project: infra
  source:
    path: charts/kube-prometheus-stack/crds
    repoURL: https://github.com/prometheus-community/helm-charts
    targetRevision: kube-prometheus-stack-45.1.1
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kube-prometheus-stack
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    chart: kube-prometheus-stack
    repoURL: https://prometheus-community.github.io/helm-charts
    targetRevision: 45.1.1
    helm:
      releaseName: kube-prometheus-stack
      skipCrds: true
      values: |
        alertmanager:
          enabled: true
        defaultRules:
          create: true
          rules:
            etcd: false
            kubeScheduler: false
        grafana:
          enabled: true
        kubeEtcd:
          enabled: false
        kubeScheduler:
          enabled: false
        prometheus:
          enabled: true
          additionalServiceMonitors:
            - name: "ambassador-monitor"
              selector:
                matchLabels:
                  service: "ambassador-admin"
              namespaceSelector:
                matchNames:
                  - ambassador
              endpoints:
                - port: "ambassador-admin"
            - name: "loki-monitor"
              selector:
                matchLabels:
                  app: loki
                  release: loki
              namespaceSelector:
                matchNames:
                  - loki-stack
              endpoints:
                - port: "http-metrics"
            - name: "promtail-monitor"
              selector:
                matchLabels:
                  app: promtail
                  release: loki
              namespaceSelector:
                matchNames:
                  - loki-stack
              endpoints:
                - port: "http-metrics"
          prometheusSpec:
            storageSpec:
              volumeClaimTemplate:
                spec:
                  accessModes:
                    - ReadWriteOnce
                  resources:
                    requests:
                      storage: 5Gi
                  storageClassName: do-block-storage
        prometheusOperator:
          enabled: true
  destination:
    server: "https://kubernetes.default.svc"
    namespace: monitoring
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true # create destination namespace if not present
